#!/bin/bash

# Your Telegram bot token
BOT_TOKEN="5812011290:AAFc1py9CQ1eY_gULz6Vhkxv5OvfuSN8ZTw"

# The chat ID of the conversation with your Telegram bot
CHAT_ID="-1001793667487"

# The URL to send the message to your Telegram bot
URL="https://api.telegram.org/bot$BOT_TOKEN/sendMessage"

# Get the current IP address of your VPS
IP_ADDRESS=$(curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//')

# Forward the IP address to the Telegram bot
curl -s -X POST $URL -d chat_id=$CHAT_ID -d text="Your VPS IP address is: $IP_ADDRESS"
